
########### Spring Cloud Stream Configuration


########## Spring Kafka Configuration (Only Used for publishing test messages)

spring:
  kafka:
    producer:
      client-id: geoapp-data-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #sasl:
      #  jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-admin" password="admin-secret";
      #  mechanism: PLAIN
      #security:
      #  protocol: SASL_PLAINTEXT
      #value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      #properties:
      #  sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-admin" password="admin-secret";
      #  sasl.mechanism: PLAIN
#        security:
#          protocol: SSL
#        auto:
#          register:
#            schemas: false
#        value:
#          subject:
#            name:
#              strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
#        schema:
#          registry:
#            url: https://schemaregistry.dev.eks.aws.cfkdev.cloud:443
#            ssl:
#              truststore:
#                location: c:/tmp/kstreams/confluent-dev/kafkaclient-truststore.jks
#                password: 
#                type: JKS
#              keystore:
#                location: c:/tmp/kstreams/confluent-dev/kafkaclient-keystore.jks
#                password: 
#        ssl:
#          truststore:
#            location: c:/tmp/kstreams/confluent-dev/kafkaclient-truststore.jks
#            password: 
#            type: JKS
#          keystore:
#            location: c:/tmp/kstreams/confluent-dev/kafkaclient-keystore.jks
#            password: 

logging:
  level:
    #org.springframework: debug
    com:
      example:
        demo:
          geoappdatagen: debug


application:
  configs:
    sensor.data.file.location: "data/messages"
    lgds.input.topic.name: lgds_events_raw
    rvss.input.topic.name: rvss_events_raw
